Traceback (most recent call last):
  File "/home/akathpalia/data/SupremeCourtTV/src/merge.py", line 803, in <module>
    final_clip = merge_videos_with_transition(video_files, data['sentences'], transition_duration=1)
  File "/home/akathpalia/data/SupremeCourtTV/src/merge.py", line 745, in merge_videos_with_transition
    clip = process_video(input_video, background_video, output_video)
  File "/home/akathpalia/data/SupremeCourtTV/src/merge.py", line 684, in process_video
    bg_clip = VideoFileClip(background_video).loop(duration=clip.duration)
  File "/home/akathpalia/miniconda3/envs/py38/lib/python3.8/site-packages/moviepy/video/io/VideoFileClip.py", line 88, in __init__
    self.reader = FFMPEG_VideoReader(filename, pix_fmt=pix_fmt,
  File "/home/akathpalia/miniconda3/envs/py38/lib/python3.8/site-packages/moviepy/video/io/ffmpeg_reader.py", line 73, in __init__
    self.lastread = self.read_frame()
  File "/home/akathpalia/miniconda3/envs/py38/lib/python3.8/site-packages/moviepy/video/io/ffmpeg_reader.py", line 133, in read_frame
    raise IOError(("MoviePy error: failed to read the first frame of "
OSError: MoviePy error: failed to read the first frame of video file src/images/background.mp4. That might mean that the file is corrupted. That may also mean that you are using a deprecated version of FFMPEG. On Ubuntu/Debian for instance the version in the repos is deprecated. Please update to a recent version from the website.
